server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
       server-addr: nacos-server:8848 # 修改本机的host 文件
      routes: # 自定义路由机制
        - id: admin-service-router   # /admin/**--->admin-service  gw-flow.json可以对整个微服务进行限流
          uri: lb://admin-service
          predicates:
            -Path = admin/**
        - id: member-service-router  # /member/**--->member-service
          uri: lb://member-service
          predicates:
            -Path = member/**
        - id: finance-service-router  # /finance/**--->finance-service
          uri: lb://finance-service
          predicates:
            - Path = finance/**
        - id: chan-service-router    # /chan/**--->chan-service
          uri: lb://chan-service
          predicates:
            - Path = chan/**
        - id: statistics-service-router # /statistics/**--->statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=statistics/**
        - id: match-service-router   # /match/**--->match-service
          uri: lb://match-service
          predicates:
            - Path=match/**
        - id: exchange-service-router  # /exchange/**--->exchange-service
          uri: lb://exchange-service
          predicates:
            - Path=match/**
        - id: test_router  # 测试路由
          uri: http://www.baidu.com
          predicates:
            - Path=/test
      sentinel:
        transport:
          dashboard: sentinel-server:8858  # sentinel-dashboard 通过nacos来持久化限流的配置
          datasource:
            #        ds1.file:
            #          file: classpath:gw-flow.json  # 网关 + API分组的限流
            #          ruleType: gw_flow
        ds1.nacos: #com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource 使用Nacos持久化我的sentinel 数据时，需要添加nacos-datasource的依赖
          serverAddr: nacos-server:8848  #可以去掉api-group gw-flow 通过nacos进行配置
          dataId: gw-flow
          ruleType: gw_flow
            #
            #        ds2.file:
            #          file: classpath:api-group.json
            #          ruleType: gw_api_group
        ds2.nacos:
          serverAddr: nacos-server:8848
          dataId: api-group
          ruleType: gw_api_group