server:
  port: 8082
spring:
  application:
    name: coin-common
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.189.133:3306/coin-exchange
    username: root
    password: 123456
  redis:
    host: 192.168.189.133
    port: 6379
    password:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8858
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password:  ${spring.redis.password}

swagger2:
  basePackage: com.worn.xiao.common.controller
  name: worn.xiao
  url:
  email:
  title: coin-common公共模块
  description: coin-common公共模块
  version: 2.0
  termsOfServiceUrl: www.wornxiao.com
